In [1]:
import pandas as pd
import numpy as np

In [ ]:
# first row contains 'Report Date'
df = pd.read_csv('data/UK-Sanctions-List.csv', skiprows=1)

C:\Users\44743\AppData\Local\Temp\ipykernel_29940\3981983569.py:2: DtypeWarning: Columns (0: IMO number, 1: Current owner/operator (s), 2: Previous owner/operator (s), 3: Current believed flag of ship, 4: Previous flags, 5: Type of ship) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/UK-Sanctions-List.csv', skiprows=1)

In [3]:
df.head()

,Last Updated,Unique ID,OFSI Group ID,UN Reference Number,Name 6,Name 1,Name 2,Name 3,Name 4,Name 5,...,IMO number,Current owner/operator (s),Previous owner/operator (s),Current believed flag of ship,Previous flags,Type of ship,Tonnage of ship,Length of ship,Year Built,Hull identification number (HIN)
0,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(57387, 58)

In [5]:
df.describe()

,OFSI Group ID,Tonnage of ship,Length of ship,Year Built,Hull identification number (HIN)
count,54805.000000,402.000000,246.000000,676.000000,0.0
mean,12413.723638,31653.631841,110.513618,2000.585799,NaN
std,2538.523624,38325.080969,42.897142,10.524330,NaN
min,6894.000000,748.000000,58.000000,1973.000000,NaN
25%,11199.000000,3037.000000,85.000000,1995.000000,NaN
50%,12446.000000,6788.000000,98.000000,2004.000000,NaN
75%,13702.000000,60303.000000,116.000000,2007.000000,NaN
max,17285.000000,164565.000000,274.500000,2024.000000,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 57387 entries, 0 to 57386
Data columns (total 58 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Last Updated                                57387 non-null  str
 1   Unique ID                                   57387 non-null  str
 2   OFSI Group ID                               54805 non-null  float64
 3   UN Reference Number                         20532 non-null  str
 4   Name 6                                      57275 non-null  str
 5   Name 1                                      24088 non-null  str
 6   Name 2                                      12242 non-null  str
 7   Name 3                                      2583 non-null   str
 8   Name 4                                      480 non-null    str
 9   Name 5                                      101 non-null    str
 10  Name type                                   57323 non-null  str
 11  Alias strength                              12982 non-null  str
 12  Title                                       2462 non-null   str
 13  Name non-latin script                       7878 non-null   str
 14  Non-latin script type                       4044 non-null   str
 15  Non-latin script language                   3602 non-null   str
 16  Regime Name                                 57387 non-null  str
 17  Designation Type                            57387 non-null  str
 18  Designation source                          57387 non-null  str
 19  Sanctions Imposed                           57387 non-null  str
 20  Other Information                           51571 non-null  str
 21  UK Statement of Reasons                     57067 non-null  str
 22  Address Line 1                              32105 non-null  str
 23  Address Line 2                              20605 non-null  str
 24  Address Line 3                              12738 non-null  str
 25  Address Line 4                              5322 non-null   str
 26  Address Line 5                              7657 non-null   str
 27  Address Line 6                              37747 non-null  str
 28  Address Postal Code                         11064 non-null  str
 29  Address Country                             45245 non-null  str
 30  Phone number                                25115 non-null  str
 31  Website                                     19335 non-null  str
 32  Email address                               24196 non-null  str
 33  Date Designated                             57387 non-null  str
 34  D.O.B                                       24943 non-null  str
 35  Nationality(/ies)                           21990 non-null  str
 36  National Identifier number                  7062 non-null   str
 37  National Identifier additional information  6762 non-null   str
 38  Passport number                             10652 non-null  str
 39  Passport additional information             9469 non-null   str
 40  Position                                    15224 non-null  str
 41  Gender                                      10799 non-null  str
 42  Town of birth                               20525 non-null  str
 43  Country of birth                            22059 non-null  str
 44  Type of entity                              16129 non-null  str
 45  Subsidiaries                                5611 non-null   str
 46  Parent company                              7775 non-null   str
 47  Business registration number (s)            4501 non-null   str
 48  IMO number                                  855 non-null    str
 49  Current owner/operator (s)                  767 non-null    str
 50  Previous owner/operator (s)                 6 non-null      str
 51  Current believed flag of ship               725 non-null    str
 52  Previous flags                              242 non-null    str
 53  Type of ship                                602 non-null    str
 54  Tonnage of ship                             402 non-null    float64
 55  Length of ship                              246 non-null    float64
 56  Year Built                                  676 non-null    float64
 57  Hull identification number (HIN)            0 non-null      float64
dtypes: float64(5), str(53)
memory usage: 25.4 MB

In [7]:
df.isnull().sum()

Last Updated                                      0
Unique ID                                         0
OFSI Group ID                                  2582
UN Reference Number                           36855
Name 6                                          112
Name 1                                        33299
Name 2                                        45145
Name 3                                        54804
Name 4                                        56907
Name 5                                        57286
Name type                                        64
Alias strength                                44405
Title                                         54925
Name non-latin script                         49509
Non-latin script type                         53343
Non-latin script language                     53785
Regime Name                                       0
Designation Type                                  0
Designation source                                0
Sanctions Imposed                                 0
Other Information                              5816
UK Statement of Reasons                         320
Address Line 1                                25282
Address Line 2                                36782
Address Line 3                                44649
Address Line 4                                52065
Address Line 5                                49730
Address Line 6                                19640
Address Postal Code                           46323
Address Country                               12142
Phone number                                  32272
Website                                       38052
Email address                                 33191
Date Designated                                   0
D.O.B                                         32444
Nationality(/ies)                             35397
National Identifier number                    50325
National Identifier additional information    50625
Passport number                               46735
Passport additional information               47918
Position                                      42163
Gender                                        46588
Town of birth                                 36862
Country of birth                              35328
Type of entity                                41258
Subsidiaries                                  51776
Parent company                                49612
Business registration number (s)              52886
IMO number                                    56532
Current owner/operator (s)                    56620
Previous owner/operator (s)                   57381
Current believed flag of ship                 56662
Previous flags                                57145
Type of ship                                  56785
Tonnage of ship                               56985
Length of ship                                57141
Year Built                                    56711
Hull identification number (HIN)              57387
dtype: int64

In [3]:
# standardize column names
df.columns = df.columns.str.replace(' ', '_').str.lower()
df = df.rename(columns={'d.o.b': 'date_of_birth', 'nationality(/ies)': 'nationality'})

df['last_updated'] = pd.to_datetime(df['last_updated'], dayfirst=True)
df['date_designated'] = pd.to_datetime(df['date_designated'], dayfirst=True)

df['name_type'] = df['name_type'].str.title()
df['ofsi_group_id'] = df['ofsi_group_id'].astype('Int64')
df['gender'] = df['gender'].str.title()
df['town_of_birth'] = df['town_of_birth'].str.strip().str.title()

# cols = ['national_identifier_number', 'passport_number']

# df[cols] = (
#     df[cols]
#     .astype('str')
#     .apply(lambda x: x.str.replace('[^a-zA-Z0-9]', '', regex=True).str.strip())
# )

df['sanctions_imposed'] = df['sanctions_imposed'].str.replace('|', ', ').str.strip()

In [4]:
df = df.drop(
    columns=['name_non-latin_script','non-latin_script_type','non-latin_script_language',
             'other_information','passport_additional_information',
             # organisation details
             'type_of_entity','subsidiaries','parent_company','business_registration_number_(s)',
             # ship details
             'imo_number','current_owner/operator_(s)','previous_owner/operator_(s)',
             'current_believed_flag_of_ship','previous_flags','type_of_ship',
             'tonnage_of_ship','length_of_ship','year_built','hull_identification_number_(hin)'
])

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 57387 entries, 0 to 57386
Data columns (total 39 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   last_updated                                57387 non-null  datetime64[us]
 1   unique_id                                   57387 non-null  str
 2   ofsi_group_id                               54805 non-null  Int64
 3   un_reference_number                         20532 non-null  str
 4   name_6                                      57275 non-null  str
 5   name_1                                      24088 non-null  str
 6   name_2                                      12242 non-null  str
 7   name_3                                      2583 non-null   str
 8   name_4                                      480 non-null    str
 9   name_5                                      101 non-null    str
 10  name_type                                   57323 non-null  str
 11  alias_strength                              12982 non-null  str
 12  title                                       2462 non-null   str
 13  regime_name                                 57387 non-null  str
 14  designation_type                            57387 non-null  str
 15  designation_source                          57387 non-null  str
 16  sanctions_imposed                           57387 non-null  str
 17  uk_statement_of_reasons                     57067 non-null  str
 18  address_line_1                              32105 non-null  str
 19  address_line_2                              20605 non-null  str
 20  address_line_3                              12738 non-null  str
 21  address_line_4                              5322 non-null   str
 22  address_line_5                              7657 non-null   str
 23  address_line_6                              37747 non-null  str
 24  address_postal_code                         11064 non-null  str
 25  address_country                             45245 non-null  str
 26  phone_number                                25115 non-null  str
 27  website                                     19335 non-null  str
 28  email_address                               24196 non-null  str
 29  date_designated                             57387 non-null  datetime64[us]
 30  date_of_birth                               24943 non-null  str
 31  nationality                                 21990 non-null  str
 32  national_identifier_number                  7062 non-null   str
 33  national_identifier_additional_information  6762 non-null   str
 34  passport_number                             10652 non-null  str
 35  position                                    15224 non-null  str
 36  gender                                      10799 non-null  str
 37  town_of_birth                               20525 non-null  str
 38  country_of_birth                            22059 non-null  str
dtypes: Int64(1), datetime64[us](2), str(36)
memory usage: 17.1 MB

In [ ]:
def combine_text_columns(df, cols):
    return (df[cols]
            .apply(lambda x: x.str.strip().str.title())
            .apply(lambda row: ' '.join(x for x in row if pd.notna(x) and x),
            axis=1
            )
    )
# name_1: first name, name_2-5: other/middle names, name_6: surname
name_cols = ['name_1', 'name_2', 'name_3', 'name_4', 'name_5', 'name_6']
address_col = ['address_line_1','address_line_2','address_line_3','address_line_4','address_line_5','address_line_6']

# df['full_name'] = combine_text_columns(df, name_cols)
# df['address'] = combine_text_columns(df, address_col)

df['full_name'] = (df[name_cols]
    .apply(lambda x: x.str.strip().str.title())
    .apply(lambda row: ' '.join(x for x in row if pd.notna(x) and x), axis=1)
)
df['address'] = (df[address_col]
    # .apply(lambda x: x.str.strip().str.title())
    .apply(lambda row: ' '.join(x.strip() for x in row if pd.notna(x) and x), axis=1)
)

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 57387 entries, 0 to 57386
Data columns (total 41 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   last_updated                                57387 non-null  datetime64[us]
 1   unique_id                                   57387 non-null  str
 2   ofsi_group_id                               54805 non-null  Int64
 3   un_reference_number                         20532 non-null  str
 4   name_6                                      57275 non-null  str
 5   name_1                                      24088 non-null  str
 6   name_2                                      12242 non-null  str
 7   name_3                                      2583 non-null   str
 8   name_4                                      480 non-null    str
 9   name_5                                      101 non-null    str
 10  name_type                                   57323 non-null  str
 11  alias_strength                              12982 non-null  str
 12  title                                       2462 non-null   str
 13  regime_name                                 57387 non-null  str
 14  designation_type                            57387 non-null  str
 15  designation_source                          57387 non-null  str
 16  sanctions_imposed                           57387 non-null  str
 17  uk_statement_of_reasons                     57067 non-null  str
 18  address_line_1                              32105 non-null  str
 19  address_line_2                              20605 non-null  str
 20  address_line_3                              12738 non-null  str
 21  address_line_4                              5322 non-null   str
 22  address_line_5                              7657 non-null   str
 23  address_line_6                              37747 non-null  str
 24  address_postal_code                         11064 non-null  str
 25  address_country                             45245 non-null  str
 26  phone_number                                25115 non-null  str
 27  website                                     19335 non-null  str
 28  email_address                               24196 non-null  str
 29  date_designated                             57387 non-null  datetime64[us]
 30  date_of_birth                               24943 non-null  str
 31  nationality                                 21990 non-null  str
 32  national_identifier_number                  7062 non-null   str
 33  national_identifier_additional_information  6762 non-null   str
 34  passport_number                             10652 non-null  str
 35  position                                    15224 non-null  str
 36  gender                                      10799 non-null  str
 37  town_of_birth                               20525 non-null  str
 38  country_of_birth                            22059 non-null  str
 39  full_name                                   57387 non-null  str
 40  address                                     57387 non-null  str
dtypes: Int64(1), datetime64[us](2), str(38)
memory usage: 18.0 MB

In [6]:
designation_drop = df[df['designation_type'].isin(['Entity', 'Ship'])].index


df.drop(designation_drop, inplace=True)

# not needed? 'title','alias_strength','un_reference_number', 'uk_statement_of_reasons', 
# 'designation_type', 'website',
# 'national_identifier_additional_information', 'designation_type'

df = df[['unique_id','ofsi_group_id',
         'full_name', 'name_type',
         'date_of_birth','nationality','gender','town_of_birth','country_of_birth',
         'phone_number','email_address',
         'national_identifier_number','passport_number',
         'address','address_postal_code','address_country',
         'regime_name','designation_source','date_designated','sanctions_imposed',
         'position','last_updated', ]]

df.to_csv('clean_individuals.csv', index=False)

In [ ]:
# pd.options.display.max_seq_items = 1600

# # sorted(df['country_of_birth'].dropna().unique())
# # sorted(df['nationality'].dropna().unique())
# # sorted(df['address_country'].dropna().unique())
# # df['sanctions_imposed'].unique()
# df['address'].unique()

<StringArray>
[                                                                                                                                                                   'Kabul',
                                                                                                                                                                         '',
                                                                                                                                                         'Darul Aman Kabul',
                                                                                                                                        'Pule Mahmood Khan PD2 10011 Kabul',
                                                                                                                                                                   ' Kabul',
                                                                                                 'Afshar Main road Police District 5 near Kabul Education University Kabul',
                                                                                                                                        'Khairkhana Section Number 3 Kabul',
                                                                                                                                 'Kushal Khan Mena District Number 5 Kabul',
                                                                                                            'Puli Charkhi Area District Number 9 Kabul City Kabul Province',
                                                                                                                                                                  'Karachi',
                                                                                                                                                      'Ibn-Sina Watt Kabul',
                                                                                                                                         'Daman District Kandahar Province',
                                                                                                                                    'Sarana Zadran Village Paktia Province',
                                                                                                                      'Kalay Rangin Spin Boldak District Kandahar Province',
                                                                                                                 'Boghra Road Miralzei Village Chaman Baluchistan Province',
                                                                                                                      'Kalay Rangin Spin Boldak District Kandahar province',
                                                                                                          'Miram Shah North Waziristan Federally Administered Tribal Areas',
                                                                                                                   'Abdul Satar Food Shop Ayno Mina 0093 Kandahar Province',
                                                                                                                                              'Chaman Baluchistan Province',
                                                                                                                     'Kachray Road Pashtunabad Quetta Baluchistan Province',
                                                                                                               'Nasrullah Khan Chowk Pashtunabad Area Baluchistan Province',
                                                                                                                'Abdul Manan Chowk Pashtunabad Quetta Baluchistan Province',
                                                                                                   'Room number 33 5th Floor Sarafi Market Kandahar City Kandahar Province',
                                                                                                                              'Wesh Spin Boldak District Kandahar Province',
                                                                                                                          'Safaar Bazaar Garmser District Helmand Province',
                                                                                                                                                                   'Quetta',
                                                                                                                       'Chalo Bawari area Quetta City Baluchistan Province',
                                                                                                              'A Haqqani Madrassa in the Afghanistan/Pakistan border area.',
                                                                                                                          'Batan village Achin District Nangarhar Province',
                                                                                                                         'Kamkai Village Achin District Nangarhar Province',
                                                                                                                        'Surkhel village Achin District Nangarhar Province',
                                                                                                                                  'Pashtunabad Quetta Baluchistan Province',
                                                                                                                                                                  'Al-Waab',
                                                                                                                                                           'Al Kharaitiyat',
                                                                                                                           'Waziristan Federally Administered Tribal Areas',
                                                                                                                                                     'P.O. Box 8096 Sana'a',
                                                                                                                        'Number 4, Via Europa, Paderno Ponchielli, Cremona',
                                                                                                                                                             'Al Moustarat',
                                                                                                                                                                      'Gao',
                                                                                                                                                                'In Khalil',
                                                                                                                                                                'Tabankort',
                                                                                                         'Podok Pesantren Al Wayain Ngrandu Sumber Agung Magetan East Java',
                                                                                                                                                                    'Daina',
                                                                                                                                                                   'Jeddah',
                                                                                                                                          'Südliche Ringstrasse 133 Langen',
                                                                                                                                                        'Ménaka Gao Region',
                                                                                                                                                  'Deir ez-Zor Governorate',
                                                                                                                                          'No.2 89th Street Zehrouni Tunis',
                                                                                                                                           '18 Mediterranean Street Ariana',
                                                                                                                                                  'Ghout El Shamal Tripoli',
                                                                                                                                                                     'Homs',
                                                                                                                                 '3111 Ma. Bautista Punta Santa Ana Manila',
                                                                                                                                                                   'London',
                                                                                                                    'House No 136 KDA Scheme No 1 Tipu Sultan Road Karachi',
                                                                                         'Akharkho Street 11 Katyr-Yurt Achkhoy-Martanovskiy District Republic of Chechnya',
                                                                                                        'Mir Ali North Waziristan Agency Federal Administered Tribal Areas',
                                                                                                                                                         'Noorabad Karachi',
                                                                                                                           'White House Near Saudi Mosque, Clifton Karachi',
                                                                                                               'House Nu 37 30th Street- defence Housing Authority Karachi',
                                                                                                                                                'Atimonana Quezon Province',
                                                                                                                                'Arbil Qushtuba house no. SH 11 alley 5380',
                                                                                                                                       'Number 5/B viale Cambonino Cremona',
                                                                                                                                 'A2, City Computer Plaza Shar-e-Now Kabul',
                                                                                                                                    'Microrayan 3rd Apt. 45 block 21 Kabul',
                                                                                                                                                   'Ganj District Peshawar',
                                                                       'Afghanistan (Kunar and Nuristan provinces and border areas of Zebok district, Badakhshan province)',
                                                                                                                              'Salam Marnaq Ben Arous district Sidi Mesoud',
                                                                                                   'House No. 116E Mohalla Johar Lahore Tehsil Lahore City Lahore District',
                                                                                                                                                           'Prison in Iraq',
                                                                                                                                         'Corso XXII Marzo Number 39 Milan',
                                                                                                                                      '50, Purdue Street Cubao Quezon City',
                                                                                                                                                               'Gaza Strip',
                                                                                                                                    'Afghanistan (as at June 2014) Tripoli',
                                                                                                                                                                'Al Rayyan',
                                                                                                                             '41-45 Rue Estienne d’Orves Pré Saint Gervais',
                                                                                         'Moscovskiy Microrayon 6 App. 96 Ust- Dzheguta Republic of Karachayevo-Cherkessia',
                                                                                                                                    'Basilan, previous location until 2016',
                                                                                                                                                            'Lanao del Sur',
                                                                                                                                            'Via Bertesi Number 27 Cremona',
                                                                                                                                          'Via Plebiscito Number 3 Cremona',
                                                                                                                                        'Sidi Argis village Oum El-Bouaghi',
                                                                                                                                                                 'Grenoble',
                                                                                                                                         'Street 13 Wazir Akbar Khan Kabul',
                                                                                                                                                                    'Mosul',
                                                                                                                                                    'Via Masina No 7 Milan',
                                                                                                           'Jalan Ir. H. Juanda 8/10 RT/RW 002/001 Jodipan Blimbing Malang',
                                                                                                           'Jalan Nakula Komplek Witana Harja III Blok C 106-107 Tangerang',
                                                                                    '90-00-04 Flat Sri Kota Bandar Tun Razak Kuala Lumpur Wilayah Persekutuan Kuala Lumpur',
                                                                                    '96-06-06 Flat Sri Kota Bandar Tun Razak Kuala Lumpur Wilayah Persekutuan Kuala Lumpur',
                                                     'B-3B-19 Glenview Villa Jalan 49 Off Jalan Kuari Taman Pinggiran Cheras Kuala Lumpur Wilayah Persekutuan Kuala Lumpur',
                                                                                                                                           'Via Della Martinella 132 Parma',
                                                                                                                                             'Cite Djenane Mabrouk Algiers',
                                                                                                                                         '50th Street No 23 Zehrouni Tunis',
                                                                                                                                 'Jamal Street Al-Dahima alley Al-Hudaydah',
                                                                                                                                                              'Sulaymaniya',
                                                                                                                                                              'East London',
                                                                                                                                                   'Ungartenstrasse 6 Bonn',
                                                                                                                                              'Amria Ben Guerdane Medenine',
                                                                                                                                                       'Al-Salibekhat area',
                                                                                                                                                                    'Raqqa',
                                                                                                                                                                   'Aleppo',
                                                                                                             'Jalan Nakula of Witana Harja Complex Block C Pamulang Banten',
                                                                                                  'Jalan M. Saidi RT010 RW 001 Pesanggrahan South Petukangan South Jakarta',
                                                                                      'Desa Cemani Waringinrejo RT 001/021 Kecamatan Grogo Kabupaten Sukoharjo Jawa Tenagh',
                                                                                          'Masjid Baitul Amin Waringinrejo RT 01 RW 02 Grogol Cemani Sukoharjo Jawa Tengah',
                                                                                                   '96 IlangIlang Sarmiento Subdivision Panabo Davao City Eastern Mindanao',
                                                                                                                              'Brgy Recodo Zamboanga City Western Mindanao',
                                                                                                                 'Block 4 Street 13 House No 179 Al-Riqqa area Kuwait City',
                                                                                                                                                                    'Amman',
                                                                                                                                                                'Khan Dari',
                                                                                                                                                 'Asas Village Abu Ghurayb',
                                                                                                                                                         'Basilan Province',
                                                                                                                                                           'Zamboanga City',
                                                                                                                                                   'Heimdalsgate 36-V Oslo',
                                                                                                                                                 'Via Plebiscito 3 Cremona',

In [19]:
primary_df = df[df['name_type'] == 'Primary Name'].copy()

aliases_df = (
    df[df['name_type'] == 'Alias']
    .groupby('ofsi_group_id')['full_name']
    .apply(lambda x: ', '.join(sorted(set(x))))
    .reset_index()
    .rename(columns={'full_name': 'aliases'})
)

In [ ]:
# def combine_unique(values):
#     return ', '.join(sorted(set(
#         str(v).strip()
#         for v in values
#         if pd.notna(v) and str(v).strip()
#     )))

def combine_unique(series):
    values = series.dropna().astype(str)

    cleaned = []
    for v in values:
        parts = [x.strip() for x in v.split(',')]
        cleaned.extend(parts)

    cleaned = [c for c in cleaned if c and c.lower() != 'nan']

    return ', '.join(sorted(set(cleaned)))

aggregated_df = df.groupby('ofsi_group_id').agg({
    'date_of_birth': combine_unique,
    'nationality': combine_unique,
    'passport_number': combine_unique,
    'national_identifier_number': combine_unique,
    'address': combine_unique,
    'address_country': combine_unique,
    'sanctions_imposed': combine_unique,
    'position': combine_unique
}).reset_index()

In [ ]:
final_df = primary_df.merge(
    aliases_df,
    on='ofsi_group_id',
    how='left'
).merge(
    aggregated_df,
    on='ofsi_group_id',
    how='left'
)

final_df = final_df.rename(columns={
    'full_name': 'primary_name'
})

In [22]:
final_df.to_csv('final.csv', index=False)

In [17]:
df.info()

<class 'pandas.DataFrame'>
Index: 26609 entries, 1021 to 57386
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   unique_id                   26609 non-null  str
 1   ofsi_group_id               26185 non-null  Int64
 2   full_name                   26609 non-null  str
 3   name_type                   26551 non-null  str
 4   date_of_birth               24943 non-null  object
 5   nationality                 21990 non-null  str
 6   gender                      10799 non-null  str
 7   town_of_birth               20525 non-null  str
 8   country_of_birth            22059 non-null  str
 9   phone_number                447 non-null    str
 10  email_address               318 non-null    str
 11  national_identifier_number  7062 non-null   str
 12  passport_number             10652 non-null  str
 13  address                     26609 non-null  str
 14  address_postal_code         1408 non-null   str
 15  address_country             16904 non-null  str
 16  regime_name                 26609 non-null  str
 17  designation_source          26609 non-null  str
 18  date_designated             26609 non-null  datetime64[us]
 19  sanctions_imposed           26609 non-null  str
 20  position                    15224 non-null  str
 21  last_updated                26609 non-null  datetime64[us]
dtypes: Int64(1), datetime64[us](2), object(1), str(18)
memory usage: 4.7+ MB